site_name: Quevedo
site_description: |
  Documentation for Quevedo: a tool for managing datasets of images with complex semantics
repo_url: https://github.com/agarsev/quevedo
nav:
  - User Guide:
    - Concepts: concepts.md
    - Step by step: User_guide.md
    - Dataset configuration: config.md
  - cli.md
  - data_augmentation.md
  - About:
    - about.md
    - license.md 
edit_uri: ''
site_dir: dist/docs
theme: readthedocs
