site_name: Quevedo Documentation
site_description: |
  Documentation for Quevedo: a tool for managing datasets of images with complex semantics
repo_url: https://github.com/agarsev/quevedo
nav:
  - Home: index.md
  - Concepts:
    - concepts.md
    - nets.md
    - pipes.md
  - Admin Guides:
    - config.md
    - cli.md
    - web.md
  - User Guides:
    - guide.md
    - web_use.md
    - dev.md
  - API:
    - Reference: api.md
edit_uri: ''
site_dir: dist/docs
theme: readthedocs
plugins:
  - mkapi:
      src_dirs: [ quevedo ]
  - mike
  - search:
      prebuild_index: true
markdown_extensions:
  - footnotes
  - admonition
  - toc:
      permalink: True
