site_name: Quevedo
site_description: |
  Documentation for Quevedo: a tool for managing datasets of images with complex semantics
repo_url: https://github.com/agarsev/quevedo
nav:
  - Home: index.md
  - Concepts:
    - concepts.md
    - nets.md
  - Usage:
    - cli.md
    - config.md
  - Guides:
    - User_guide.md
edit_uri: ''
site_dir: dist/docs
theme: readthedocs
markdown_extensions:
  - footnotes
  - admonition
