site_name: Quevedo Documentation
site_description: |
  Documentation for Quevedo: a tool for managing datasets of images with complex semantics
repo_url: https://github.com/agarsev/quevedo
nav:
  - Home: index.md
  - Concepts:
    - concepts.md
    - nets.md
  - Usage:
    - config.md
    - cli.md
    - web.md
  - Guides:
    - web_use.md
    - dev.md
    - User_guide.md
    - with_dvc.md
  - API: api.md
edit_uri: ''
site_dir: dist/docs
theme: readthedocs
plugins:
  - mkapi:
      src_dirs: [ quevedo ]
markdown_extensions:
  - footnotes
  - admonition
  - toc:
      permalink: True
