#+title: Roadmap

* Next

** TODO Web interface improvements

*** TODO Filter/search annotations in listing according to some tag(s).

*** TODO Autosuggest values for tagging
maybe use https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

*** TODO Improve messaging
Remove "saved" message when doing changes (inconsistent), maybe load indicator

*** TODO Allow deleting entries
Maybe just move the last to the hole?

*** TODO Better mobile interface
Maybe integrate with camera/scan app, make quevedo a target for "sharing"
(uploading) images.

*** TODO Web user improvements
User groups, record annotator in json.

*** TODO Documentation

- [ ] "flags" (from v1.1)
- [ ] changes from v1.2

** TODO Improve use of scripts when modifing images

When scripts modify images, don't save them, but return that it has been
modified (ie return modified_tags, modified_img) and then it is `run_script`
that saves the image to the appropriate path. Coversely, in the web interface
the updated image can be sent to the frontend to be previewed, and if they want
to save it send it back to the server on "save". The complication is that the
image is now frontend state, not just a src link.
